// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
	schema: "prisma/dbLumilaya/schema.prisma",
	migrations: {
		path: "prisma/dbLumilaya/migrations",
	},
	datasource: {
		url: process.env.DATABASE_URL_DBLUMILAYA,
	},
});
